# Generated by Django 4.2.6 on 2024-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_type', models.CharField(max_length=255)),
                ('categories_description', models.TextField()),
                ('category_image', models.ImageField(upload_to='category_images/%y')),
            ],
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=255)),
                ('fact', models.TextField()),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_type', models.CharField(max_length=100)),
                ('animal_cat', models.CharField(max_length=50)),
                ('animal', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('date_discovered', models.CharField(max_length=100)),
                ('discovered_by', models.CharField(max_length=100)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('image_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
